language: python
python:
  - 2.7.15
dist: trusty
env:
# QA Tests target environments: allowed value are 'boly38' or 'master'
  - TARGET_ENV=master
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - xvfb
install:
  - pip install --upgrade pip
  - pip -V
  - pip install -r requirements.txt
before_script:
  - echo ${OS}
  - wget "http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - touch ./scripts/.requirements_checked
jobs:
  include:
  - stage: qaTests
    name: "execute tests"
    script:
    - ./scripts/getPreviousReport.sh && ./scripts/runTests.sh && ./scripts/publishReport.sh && ./scripts/checkResults.sh

notifications:
  irc:
      channels:
          - "chat.freenode.net#geokrety"
      on_success: always
      on_failure: always
      template:
          - "%{build_url} QA %{build_number} | %{branch} | %{commit_subject} | %{result}"
