language: python
python:
  - 2.7.15
dist: trusty
env:
# QA Tests target environments: allowed value are 'boly38' or 'master'
  - TARGET_ENV=master
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - pip install --upgrade pip
  - pip -V
  - pip install -r requirements.txt
before_script:
  - echo ${OS}
  - wget "http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - touch ./.requirements_checked
script:
  - bash ./getPreviousReport.sh
  - bash ./runTests.sh
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  keep-history: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|feature\/report$
notifications:
  email:
    - boly38@gmail.com
  irc:
      channels:
          - "chat.freenode.net#geokrety"
      on_success: change
      on_failure: always
      template:
          - "%{branch} / %{result} / %{build_url}"
